#Travis CI configuration for VXL
# See http://travis-ci.org/vxl/vxl

sudo: false

language: cpp
compiler:
  - gcc
  - clang

cache:
  - ccache
  - directories:
    - $HOME/deps

before_script:
  - bash .travis/install-deps.sh

addons:
  apt:
    packages:
    - ccache

script:
  - export PATH=$HOME/deps/bin:$PATH
  - mkdir build
  - mkdir $HOME/install
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/install
          ../
  - make -j2
  - ctest
  - make install
